In [2]:
import duckdb
import pandas as pd

In [30]:
sql_query = '''
show tables
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                              name
0   bronze_parking_violation_codes
1        bronze_parking_violations
2                      first_model
3              gold_ticket_metrics
4             gold_vehicle_metrics
5               my_first_dbt_model
6              my_second_dbt_model
7          parking_violation_codes
8          parking_violations_2023
9                        ref_model
10  silver_parking_violation_codes
11       silver_parking_violations
12        silver_violation_tickets
13       silver_violation_vehicles

In [12]:
import duckdb

# Connect to your DuckDB database
db_path = "data/nyc_parking_violations.db"
with duckdb.connect(db_path) as con:
    # Get all tables and views from the main schema
    objects = con.execute("""
        SELECT table_name, table_type 
        FROM information_schema.tables 
        WHERE table_schema = 'main'
    """).fetchall()

    # Drop each table or view
    for table_name, table_type in objects:
        if table_type.upper() == 'VIEW':
            con.execute(f"DROP VIEW IF EXISTS {table_name}")
        elif table_type.upper() == 'BASE TABLE':
            con.execute(f"DROP TABLE IF EXISTS {table_name}")

In [17]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT *
from read_csv_auto('data/dof_parking_violation_codes.csv', 
normalize_names=True)
'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violations_2023 AS
SELECT *
from read_csv_auto('data/parking_violations_issued_fiscal_year_2023_sample.csv',
normalize_names=True)
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
  con.sql(sql_query_import_1)
  con.sql(sql_query_import_2)

In [29]:
sql_query = '''
select * from gold_vehicle_metrics limit 3
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

  registration_state  ticket_count
0                 NJ          9258
1                 PA          3514
2                 FL          2414

In [35]:
sql_query = '''
select * from "nyc_parking_violations"."main_dbt_test__audit"."violation_codes_revenue"
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
  display(con.sql(sql_query))

┌────────────────┬───────────────────┐
│ violation_code │ total_revenue_usd │
│     int64      │      int128       │
├────────────────┼───────────────────┤
│             41 │                 0 │
└────────────────┴───────────────────┘

In [36]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT *
from read_csv_auto('data/dof_parking_violation_codes.csv', 
normalize_names=True)
'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violations_2023 AS
SELECT *
from read_csv_auto('data/parking_violations_issued_fiscal_year_2023_sample.csv',
normalize_names=True)
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
  con.sql(sql_query_import_1)
  con.sql(sql_query_import_2)

In [37]:
sql_query = '''
show tables
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                             name
0  bronze_parking_violation_codes
1       bronze_parking_violations
2             gold_ticket_metrics
3            gold_vehicle_metrics
4           gold_vehicles_metrics
5         parking_violation_codes
6         parking_violations_2023
7        silver_violation_tickets
8       silver_violation_vehicles

In [39]:
sql_query = '''
select count(*) as count
from prod_nyc_parking_violations.bronze_parking_violation_codes
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

   count
0     97

In [40]:
sql_query = '''
select count(*) as count
from prod_nyc_parking_violations.gold_ticket_metrics
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

   count
0     76