In [2]:
import duckdb
import pandas as pd

In [19]:
sql_query = '''
SELECT * FROM gold_vehicles_metrics LIMIT 5
'''

with duckdb.connect('nyc_parking_violations/data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

  registration_state  ticket_count
0                 NJ          9258
1                 PA          3514
2                 FL          2414
3                 CT          1787
4                 GA           840

In [19]:
# Replace 'table_name' with the name of the table/view you want to delete
table_name = 'silver_violation_vehicles'

with duckdb.connect('data/nyc_parking_violations.db') as con:
  con.sql(f'DROP VIEW IF EXISTS {table_name}')
  print(f"Deleted view: {table_name}")

Deleted view: silver_violation_vehicles

In [21]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS 
SELECT * 
FROM read_csv_auto('data/dof_parking_violation_codes.csv', normalize_names=TRUE)
'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violations_2023 AS
SELECT *
FROM read_csv_auto('data/parking_violations_issued_fiscal_year_2023_sample.csv', normalize_names=TRUE)
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    con.sql(sql_query_import_1)
    con.sql(sql_query_import_2)
    print("Imported CSV files into DuckDB tables.")

Imported CSV files into DuckDB tables.

In [9]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS 
SELECT * 
FROM read_csv_auto('nyc_parking_violations/data/dof_parking_violation_codes.csv', normalize_names=TRUE)
'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violations_2023 AS
SELECT *
FROM read_csv_auto('nyc_parking_violations/data/parking_violations_issued_fiscal_year_2023_sample.csv', normalize_names=TRUE)
'''

with duckdb.connect('nyc_parking_violations/data/prod_nyc_parking_violations.db') as con:
    con.sql(sql_query_import_1)
    con.sql(sql_query_import_2)
    print("Imported CSV files into DuckDB tables.")

Imported CSV files into DuckDB tables.

In [11]:
sql_query = '''
SHOW TABLES
'''

with duckdb.connect('nyc_parking_violations/data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                             name
0  bronze_parking_violation_codes
1       bronze_parking_violations
2             gold_ticket_metrics
3           gold_vehicles_metrics
4         parking_violation_codes
5         parking_violations_2023
6        silver_violation_tickets
7       silver_violation_vehicles